name = "BridgeStan"
uuid = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
authors = [
    "Brian Ward <bward@flatironinstitute.org>",
    "Bob Carpenter <bcarpenter@flatironinstitute.org>",
    "Edward Roualdes <eroualdes@csuchico.edu>",
]
version = "2.6.1"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
Downloads = "1"
TOML = "1"
Inflate = "0.1"
Tar = "1"
julia = "1.6"
